package cmd

import (
	"fmt"
	"io"
	"strconv"
	"strings"

	"github.com/TuftsBCB/io/pdb"
)

// writePDBToWriter writes a PDB entry to the given writer, preserving ALTLOC fields
func writePDBToWriter(entry *pdb.Entry, writer io.Writer, commandLine string) error {
	return writePDBToWriterWithAltLoc(entry, nil, nil, nil, writer, commandLine)
}

// writePDBToWriterWithAltLoc writes a PDB entry to the given writer, preserving ALTLOC fields,
// optionally appending HETATM lines from HetRecord (already filtered; serial numbers renumbered)
// and LINK lines when both bond sites are present in the written coordinates and kept hetero set.
func writePDBToWriterWithAltLoc(entry *pdb.Entry, altLocList []byte, hetRecords []HetRecord, linkLines []string, writer io.Writer, commandLine string) error {
	fmt.Fprintf(writer, "HEADER    %s\n", entry.IdCode)
	fmt.Fprintf(writer, "REMARK   1 GENERATED BY PDBTK\n")
	fmt.Fprintf(writer, "REMARK   1 COMMAND: %s\n", commandLine)
	fmt.Fprintf(writer, "REMARK   1\n")

	hasMultipleModels := false
	for _, chain := range entry.Chains {
		if len(chain.Models) > 1 {
			hasMultipleModels = true
			break
		}
	}

	lastChainIdx, lastModelIdx := -1, -1
	for ci, chain := range entry.Chains {
		for mi := range chain.Models {
			lastChainIdx, lastModelIdx = ci, mi
		}
	}

	atomSerial := 1
	for ci, chain := range entry.Chains {
		for mi, model := range chain.Models {
			if hasMultipleModels {
				fmt.Fprintf(writer, "MODEL     %4d\n", model.Num)
			}

			for _, residue := range model.Residues {
				for _, atom := range residue.Atoms {
					recordType := "ATOM  "
					if atom.Het {
						recordType = "HETATM"
					}
					insertionCode := residue.InsertionCode
					if insertionCode == 0 {
						insertionCode = ' '
					}

					var altLoc byte = ' '
					if altLocList != nil && atomSerial-1 < len(altLocList) {
						altLoc = altLocList[atomSerial-1]
					} else {
						altLoc = ExtractAltLocFromAtomName(atom.Name)
					}
					cleanAtomName := RemoveAltLocFromAtomName(atom.Name)

					fmt.Fprintf(writer, "%-6s%5d %s%c%3s %c%4d%c   %8.3f%8.3f%8.3f%6.2f%6.2f          %2s\n",
						recordType,
						atomSerial,
						formatAtomName(cleanAtomName),
						altLoc,
						singleLetterToResidue(string(byte(residue.Name))),
						chain.Ident,
						residue.SequenceNum,
						insertionCode,
						atom.Coords.X, atom.Coords.Y, atom.Coords.Z,
						1.00, 20.00,
						extractElementSymbol(cleanAtomName),
					)
					atomSerial++
				}
			}

			if hasMultipleModels {
				if ci == lastChainIdx && mi == lastModelIdx {
					if len(hetRecords) > 0 {
						atomSerial = writeHetatmRenumbered(writer, hetRecords, atomSerial)
					}
					writeLINKLines(writer, linkLines)
				}
				fmt.Fprintf(writer, "ENDMDL\n")
			}
		}
	}

	if !hasMultipleModels {
		if len(hetRecords) > 0 {
			writeHetatmRenumbered(writer, hetRecords, atomSerial)
		}
		writeLINKLines(writer, linkLines)
	}

	fmt.Fprintf(writer, "END\n")
	return nil
}

func writeLINKLines(w io.Writer, lines []string) {
	for _, line := range lines {
		fmt.Fprintf(w, "%s\n", strings.TrimRight(line, "\r"))
	}
}

func writeHetatmRenumbered(w io.Writer, recs []HetRecord, startSerial int) int {
	n := startSerial
	for _, r := range recs {
		fmt.Fprintf(w, "%s\n", formatHetatmRenumberedLine(r.Raw, n))
		n++
	}
	return n
}

func formatHetatmRenumberedLine(raw string, serial int) string {
	b := []byte(strings.TrimRight(raw, "\r\n"))
	if len(b) < 11 {
		return string(b)
	}
	for len(b) < 80 {
		b = append(b, ' ')
	}
	ds := strconv.Itoa(serial)
	if len(ds) > 5 {
		ds = ds[len(ds)-5:]
	}
	serialField := fmt.Sprintf("%5s", ds)
	copy(b[6:11], []byte(serialField))
	return strings.TrimRight(string(b), " ")
}

func ExtractAltLocFromAtomName(atomName string) byte {
	name := strings.TrimSpace(atomName)
	if len(name) >= 3 {
		lastChar := name[len(name)-1]
		if lastChar >= 'A' && lastChar <= 'Z' {
			return lastChar
		}
	}
	return ' '
}

func RemoveAltLocFromAtomName(atomName string) string {
	name := strings.TrimSpace(atomName)
	if len(name) >= 3 {
		lastChar := name[len(name)-1]
		if lastChar >= 'A' && lastChar <= 'Z' {
			return strings.TrimSpace(name[:len(name)-2])
		}
	}
	return name
}

func extractElementSymbol(atomName string) string {
	atomName = strings.TrimSpace(atomName)
	if len(atomName) == 0 {
		return ""
	}

	for i, char := range atomName {
		if (char >= 'A' && char <= 'Z') || (char >= 'a' && char <= 'z') {
			if i+1 < len(atomName) && atomName[i+1] >= 'a' && atomName[i+1] <= 'z' {
				return strings.ToUpper(atomName[i : i+2])
			}
			return strings.ToUpper(string(char))
		}
	}

	if len(atomName) > 0 {
		return strings.ToUpper(string(atomName[0]))
	}
	return ""
}

func singleLetterToResidue(singleLetter string) string {
	singleLetter = strings.ToUpper(singleLetter)

	reverseMap := map[string]string{
		"A": "ALA", "R": "ARG", "N": "ASN", "D": "ASP", "C": "CYS",
		"Q": "GLN", "E": "GLU", "G": "GLY", "H": "HIS", "I": "ILE",
		"L": "LEU", "K": "LYS", "M": "MET", "F": "PHE", "P": "PRO",
		"S": "SER", "T": "THR", "W": "TRP", "Y": "TYR", "V": "VAL",
		"U": "SEC", "O": "PYL",
		"X": "UNK", "J": "XLE",
	}

	if threeLetter, exists := reverseMap[singleLetter]; exists {
		return threeLetter
	}

	return "UNK"
}

func formatAtomName(atomName string) string {
	name := strings.TrimSpace(atomName)
	element := extractElementSymbol(name)

	if len(name) >= 4 {
		return fmt.Sprintf("%-4s", name)
	}

	if len(element) == 1 {
		trailing := strings.TrimPrefix(name, element)
		return fmt.Sprintf(" %-1s%-2s", element, trailing)
	}

	if len(element) == 2 {
		trailing := strings.TrimPrefix(name, element)
		return fmt.Sprintf("%-2s%-2s", element, trailing)
	}

	return fmt.Sprintf("%-4s", name)
}
