package tests

import (
	"os"
	"os/exec"
	"strings"
	"testing"

	"github.com/perry/pdbtk/pdbtk/cmd"
)

func TestExtractCommand(t *testing.T) {
	// Create a temporary test PDB file
	testPDB := `HEADER    TEST STRUCTURE                                   01-JAN-01   TEST
ATOM      1  N   ALA A   1      20.154  16.967  23.862  1.00 11.18           N
ATOM      2  CA  ALA A   1      19.030  16.206  23.362  1.00 10.53           C
ATOM      3  C   ALA A   1      17.680  16.889  23.362  1.00 10.53           C
ATOM      4  O   ALA A   1      17.680  18.089  23.362  1.00 10.53           O
ATOM      5  N   VAL B   1      30.154  26.967  33.862  1.00 11.18           N
ATOM      6  CA  VAL B   1      29.030  26.206  33.362  1.00 10.53           C
ATOM      7  C   VAL B   1      27.680  26.889  33.362  1.00 10.53           C
ATOM      8  O   VAL B   1      27.680  28.089  33.362  1.00 10.53           O
END`

	// Write test file
	err := os.WriteFile("test.pdb", []byte(testPDB), 0644)
	if err != nil {
		t.Fatalf("Failed to create test file: %v", err)
	}
	defer os.Remove("test.pdb")

	// Test file existence check
	err = cmd.CheckFileExists("test.pdb")
	if err != nil {
		t.Errorf("checkFileExists failed for existing file: %v", err)
	}

	err = cmd.CheckFileExists("nonexistent.pdb")
	if err == nil {
		t.Error("checkFileExists should fail for nonexistent file")
	}
}

func TestExtractCommandOutput(t *testing.T) {
	// Create a temporary test PDB file with multiple chains
	testPDB := `HEADER    TEST STRUCTURE                                   01-JAN-01   TEST
ATOM      1  N   ALA A   1      20.154  16.967  23.862  1.00 11.18           N
ATOM      2  CA  ALA A   1      19.030  16.206  23.362  1.00 10.53           C
ATOM      3  C   ALA A   1      17.680  16.889  23.362  1.00 10.53           C
ATOM      4  O   ALA A   1      17.680  18.089  23.362  1.00 10.53           O
ATOM      5  N   VAL B   1      30.154  26.967  33.862  1.00 11.18           N
ATOM      6  CA  VAL B   1      29.030  26.206  33.362  1.00 10.53           C
ATOM      7  C   VAL B   1      27.680  26.889  33.362  1.00 10.53           C
ATOM      8  O   VAL B   1      27.680  28.089  33.362  1.00 10.53           O
END`

	// Write test file
	err := os.WriteFile("test_extract.pdb", []byte(testPDB), 0644)
	if err != nil {
		t.Fatalf("Failed to create test file: %v", err)
	}
	defer os.Remove("test_extract.pdb")

	// Test extracting chain A
	cmd := exec.Command("../bin/pdbtk", "extract", "--chains", "A", "test_extract.pdb")
	output, err := cmd.Output()
	if err != nil {
		t.Fatalf("Failed to run extract command: %v", err)
	}

	outputStr := string(output)
	lines := strings.Split(outputStr, "\n")

	// Check that we have a proper header
	if !strings.Contains(outputStr, "HEADER") {
		t.Error("Output should contain HEADER line")
	}

	// Check that we have REMARK lines
	if !strings.Contains(outputStr, "REMARK   1 GENERATED BY PDBTK") {
		t.Error("Output should contain REMARK line")
	}

	// Check that we have ATOM lines
	atomLines := 0
	hasNonZeroCoords := false
	for _, line := range lines {
		if strings.HasPrefix(line, "ATOM") {
			atomLines++
			// Check that coordinates are not all zeros
			if strings.Contains(line, "20.154") || strings.Contains(line, "19.030") || strings.Contains(line, "17.680") {
				hasNonZeroCoords = true
			}
			// Check that we only have chain A atoms
			if strings.Contains(line, " A ") {
				// This is expected
			} else if strings.Contains(line, " B ") {
				t.Error("Chain A extraction should not contain chain B atoms")
			}
		}
	}

	if atomLines == 0 {
		t.Error("Output should contain ATOM lines")
	}

	if !hasNonZeroCoords {
		t.Error("Output should contain atoms with non-zero coordinates")
	}

	// Test extracting chain B
	cmd = exec.Command("../bin/pdbtk", "extract", "--chains", "B", "test_extract.pdb")
	output, err = cmd.Output()
	if err != nil {
		t.Fatalf("Failed to run extract command for chain B: %v", err)
	}

	outputStr = string(output)
	lines = strings.Split(outputStr, "\n")

	// Check that we have ATOM lines for chain B
	hasChainBAtoms := false
	for _, line := range lines {
		if strings.HasPrefix(line, "ATOM") && strings.Contains(line, " B ") {
			hasChainBAtoms = true
			// Check that coordinates are not all zeros
			if strings.Contains(line, "30.154") || strings.Contains(line, "29.030") || strings.Contains(line, "27.680") {
				// This is expected
			}
		}
	}

	if !hasChainBAtoms {
		t.Error("Chain B extraction should contain chain B atoms")
	}
}

func countHetatmLines(output string) int {
	n := 0
	for _, line := range strings.Split(output, "\n") {
		if strings.HasPrefix(line, "HETATM") {
			n++
		}
	}
	return n
}

func countLINKLines(output string) int {
	n := 0
	for _, line := range strings.Split(output, "\n") {
		if strings.HasPrefix(line, "LINK") {
			n++
		}
	}
	return n
}

func TestExtractKeepHetatmFlags(t *testing.T) {
	testPDB := `HEADER    TEST STRUCTURE                                   01-JAN-01   TEST
ATOM      1  N   ALA A   1      10.000  10.000  10.000  1.00 11.18           N  
ATOM      2  CA  ALA A   1      11.000  10.000  10.000  1.00 10.53           C  
TER   38911      MET J 317                                                       
LINK         CA  ALA A   1                ZN    ZN A  99     1555   1555   1.93
HETATM   98  ZN   ZN A  99      20.000  20.000  20.000  1.00 36.00           ZN  
ATOM     99  N   VAL B   1      30.000  26.967  33.862  1.00 11.18           N  
ATOM    100  CA  VAL B   1      31.000  26.206  33.362  1.00 10.53           C  
TER   38912      MET J 318                                                       
HETATM  101  O   HOH A 100      40.000  40.000  40.000  1.00 36.00           O  
HETATM  107  C2  LIG B 200      50.000  50.000  50.000  1.00 36.00           O  
END
`
	err := os.WriteFile("test_extract_het.pdb", []byte(testPDB), 0644)
	if err != nil {
		t.Fatalf("Failed to create test file: %v", err)
	}
	defer os.Remove("test_extract_het.pdb")

	run := func(args ...string) (string, error) {
		cmd := exec.Command("../bin/pdbtk", args...)
		out, err := cmd.CombinedOutput()
		return string(out), err
	}

	out, err := run("extract", "--chains", "A", "test_extract_het.pdb")
	if err != nil {
		t.Fatalf("extract: %v\n%s", err, out)
	}
	if countHetatmLines(out) != 0 {
		t.Fatalf("expected 0 HETATM without keep flags, got %d", countHetatmLines(out))
	}
	if countLINKLines(out) != 0 {
		t.Fatalf("expected no LINK lines without keep-hetatm, got %d", countLINKLines(out))
	}

	out, err = run("extract", "--chains", "A", "--keep-hetatm", "test_extract_het.pdb")
	if err != nil {
		t.Fatalf("extract keep-hetatm: %v\n%s", err, out)
	}
	if n := countHetatmLines(out); n != 1 {
		t.Fatalf("expected 1 non-water HETATM for chain A, got %d", n)
	}
	if !strings.Contains(out, " ZN ") || strings.Contains(out, "HOH") {
		t.Fatalf("expected ZN hetero without HOH, output:\n%s", out)
	}
	if countLINKLines(out) != 1 || !strings.Contains(out, "LINK") {
		t.Fatalf("expected exactly one LINK with --keep-hetatm chain A, output:\n%s", out)
	}

	out, err = run("extract", "--chains", "A", "--keep-waters", "test_extract_het.pdb")
	if err != nil {
		t.Fatalf("extract keep-waters: %v\n%s", err, out)
	}
	if n := countHetatmLines(out); n != 1 {
		t.Fatalf("expected 1 water HETATM for chain A, got %d", n)
	}
	if !strings.Contains(out, "HOH") || strings.Contains(out, "LIG") {
		t.Fatalf("expected HOH without LIG, output:\n%s", out)
	}
	if countLINKLines(out) != 0 {
		t.Fatalf("expected no LINK lines with --keep-waters only")
	}

	out, err = run("extract", "--chains", "A", "--keep-hetatm", "--keep-waters", "test_extract_het.pdb")
	if err != nil {
		t.Fatalf("extract both keeps: %v\n%s", err, out)
	}
	if n := countHetatmLines(out); n != 2 {
		t.Fatalf("expected 2 HETATM (LIG + HOH), got %d", n)
	}
	if strings.Contains(out, "LIG B") || strings.Contains(out, "HOH B") {
		t.Fatalf("chain B hetero leaked into chain A extraction:\n%s", out)
	}

	out, err = run("extract", "--keep-hetatm", "test_extract_het.pdb")
	if err != nil {
		t.Fatalf("extract keep-hetatm all chains: %v\n%s", err, out)
	}
	if n := countHetatmLines(out); n != 2 {
		t.Fatalf("expected non-water ligands on A and B, got %d HETATM", n)
	}
	if !strings.Contains(out, "ZN A") || !strings.Contains(out, "LIG B") {
		t.Fatalf("expected ZN on chain A and LIG on chain B, output:\n%s", out)
	}
}
