package structure

import (
	"bufio"
	"fmt"
	"io"
	"strings"
)

// WriteOptions controls provenance and lossy-conversion behaviour shared by
// both writers.
type WriteOptions struct {
	CommandLine string
	Version     string

	// ForceLossy permits writing PDB output that cannot faithfully represent
	// the structure (see FitPDB). Without it, WritePDB returns an error.
	ForceLossy bool

	// Warn receives human-readable notices about lossy conversions. May be nil.
	Warn func(string)
}

func (o WriteOptions) warn(format string, args ...interface{}) {
	if o.Warn != nil {
		o.Warn(fmt.Sprintf(format, args...))
	}
}

// FitPDB reports the ways in which a structure cannot be represented in the
// legacy PDB format. An empty result means the structure fits exactly.
func FitPDB(s *Structure) []string {
	var problems []string
	seen := make(map[string]bool)
	add := func(format string, args ...interface{}) {
		msg := fmt.Sprintf(format, args...)
		if !seen[msg] {
			seen[msg] = true
			problems = append(problems, msg)
		}
	}

	if _, ok := encodeHybrid36(len(s.Atoms), 5); !ok {
		add("%d atoms exceeds what a PDB atom serial field can encode", len(s.Atoms))
	}
	for _, a := range s.Atoms {
		if len(a.ChainID) > 1 {
			add("chain ID %q is longer than one character", a.ChainID)
		}
		if len(a.ResName) > 3 {
			add("residue name %q is longer than three characters", a.ResName)
		}
		if len(a.Name) > 4 {
			add("atom name %q is longer than four characters", a.Name)
		}
		if len(a.AltLoc) > 1 {
			add("altLoc %q is longer than one character", a.AltLoc)
		}
		if _, ok := encodeHybrid36(a.ResSeq, 4); !ok {
			add("residue number %d does not fit a PDB residue sequence field", a.ResSeq)
		}
	}
	return problems
}

// WritePDB serialises a structure as a legacy PDB file. Atom serials are
// renumbered sequentially from 1.
func WritePDB(w io.Writer, s *Structure, opt WriteOptions) error {
	problems := FitPDB(s)
	if len(problems) > 0 && !opt.ForceLossy {
		return fmt.Errorf("structure cannot be represented in PDB format:\n  - %s\n"+
			"write mmCIF instead (--out-format cif), or pass --force-lossy-pdb to convert anyway",
			strings.Join(problems, "\n  - "))
	}

	bw := bufio.NewWriter(w)
	defer bw.Flush()

	id := s.ID
	if id == "" {
		id = "XXXX"
	}
	// HEADER carries the ID code in columns 63-66; classification and deposition
	// date are left blank since pdbtk does not track them.
	fmt.Fprintf(bw, "HEADER%s%-4s\n", strings.Repeat(" ", 56), truncate(id, 4))
	fmt.Fprintf(bw, "REMARK   1 GENERATED BY PDBTK %s\n", opt.Version)
	fmt.Fprintf(bw, "REMARK   1 COMMAND: %s\n", opt.CommandLine)
	for _, p := range problems {
		opt.warn("lossy PDB conversion: %s", p)
		fmt.Fprintf(bw, "REMARK   1 LOSSY CONVERSION: %s\n", strings.ToUpper(p))
	}
	fmt.Fprintf(bw, "REMARK   1\n")

	writeSEQRES(bw, s)
	writeLINKs(bw, s)

	multiModel := s.HasMultipleModels()
	serial := 0
	curModel := 0
	openModel := false

	// A TER record closes each run of polymer atoms, so track the last ATOM
	// seen in the current chain to fill its residue fields.
	var pendingTER *Atom
	flushTER := func() {
		if pendingTER == nil {
			return
		}
		serial++
		fmt.Fprintf(bw, "TER   %s      %3s %s%s%s\n",
			mustEncode(serial, 5),
			truncate(pendingTER.ResName, 3),
			padChain(pendingTER.ChainID),
			mustEncode(pendingTER.ResSeq, 4),
			padCol(pendingTER.InsCode),
		)
		pendingTER = nil
	}

	for _, a := range s.Atoms {
		if multiModel && a.Model != curModel {
			flushTER()
			if openModel {
				fmt.Fprintf(bw, "ENDMDL\n")
			}
			fmt.Fprintf(bw, "MODEL     %4d\n", a.Model)
			curModel, openModel = a.Model, true
		}

		// TER closes the polymer run: it precedes any hetero atoms of the same
		// chain, as well as the start of a new chain.
		if pendingTER != nil && (a.Hetatm || a.ChainID != pendingTER.ChainID || a.Model != pendingTER.Model) {
			flushTER()
		}

		serial++
		writeAtomLine(bw, a, serial)

		if !a.Hetatm {
			pendingTER = a
		}
	}
	flushTER()
	if openModel {
		fmt.Fprintf(bw, "ENDMDL\n")
	}

	fmt.Fprintf(bw, "END\n")
	return bw.Flush()
}

func writeAtomLine(bw *bufio.Writer, a *Atom, serial int) {
	record := "ATOM  "
	if a.Hetatm {
		record = "HETATM"
	}
	occ, temp := a.Occupancy, a.BFactor
	if !a.HasOcc {
		occ = 1.00
	}
	if !a.HasB {
		temp = 0.00
	}
	fmt.Fprintf(bw, "%s%s %s%s%3s %s%s%s   %8.3f%8.3f%8.3f%6.2f%6.2f          %2s%-2s\n",
		record,
		mustEncode(serial, 5),
		formatAtomName(a),
		padCol(a.AltLoc),
		truncate(a.ResName, 3),
		padChain(a.ChainID),
		mustEncode(a.ResSeq, 4),
		padCol(a.InsCode),
		a.X, a.Y, a.Z,
		occ, temp,
		truncate(strings.ToUpper(a.Element), 2),
		truncate(a.Charge, 2),
	)
}

func writeSEQRES(bw *bufio.Writer, s *Structure) {
	for _, cs := range s.SeqRes {
		chain := padChain(cs.ChainID)
		for i, line := 0, 1; i < len(cs.Residues); i, line = i+13, line+1 {
			end := i + 13
			if end > len(cs.Residues) {
				end = len(cs.Residues)
			}
			var b strings.Builder
			for _, r := range cs.Residues[i:end] {
				fmt.Fprintf(&b, " %3s", truncate(r, 3))
			}
			fmt.Fprintf(bw, "SEQRES %3d %s %4d %s\n", line, chain, len(cs.Residues), b.String())
		}
	}
}

func writeLINKs(bw *bufio.Writer, s *Structure) {
	for _, l := range s.Links {
		dist := "     "
		if l.HasDist {
			dist = fmt.Sprintf("%5.2f", l.Distance)
		}
		fmt.Fprintf(bw, "LINK        %s%s%3s %s%s%s               %s%s%3s %s%s%s  %-6s %-6s %s\n",
			formatAtomNameRef(l.A), padCol(l.A.AltLoc), truncate(l.A.ResName, 3),
			padChain(l.A.ChainID), mustEncode(l.A.ResSeq, 4), padCol(l.A.InsCode),
			formatAtomNameRef(l.B), padCol(l.B.AltLoc), truncate(l.B.ResName, 3),
			padChain(l.B.ChainID), mustEncode(l.B.ResSeq, 4), padCol(l.B.InsCode),
			l.A.SymOp, l.B.SymOp, dist)
	}
}

// formatAtomName restores the PDB column convention: two-character element
// symbols start in column 13, everything else is indented one column so the
// element letter sits in column 14.
func formatAtomName(a *Atom) string {
	return justifyAtomName(a.Name, a.Element)
}

func formatAtomNameRef(r AtomRef) string {
	return justifyAtomName(r.AtomName, "")
}

func justifyAtomName(name, element string) string {
	name = strings.TrimSpace(name)
	if len(name) >= 4 {
		return truncate(name, 4)
	}
	el := strings.ToUpper(strings.TrimSpace(element))
	if len(el) == 2 && strings.HasPrefix(strings.ToUpper(name), el) {
		return fmt.Sprintf("%-4s", name)
	}
	return fmt.Sprintf(" %-3s", name)
}

// mustEncode renders a value into a fixed-width field, falling back to a run of
// asterisks if even hybrid-36 cannot hold it. Callers reach this only in
// --force-lossy-pdb mode, since FitPDB rejects such values otherwise.
func mustEncode(v, width int) string {
	if s, ok := encodeHybrid36(v, width); ok {
		return s
	}
	return strings.Repeat("*", width)
}

func padCol(s string) string {
	if s == "" {
		return " "
	}
	return s[:1]
}

func padChain(s string) string {
	if s == "" {
		return " "
	}
	return s[:1]
}

func truncate(s string, n int) string {
	if len(s) > n {
		return s[:n]
	}
	return s
}
